### ISSUE TITLE
微信小程序请求支持transition

### ISSUE THREAD

**Issue by Chandlercjy** [AdvancedCat/taro-vue-router#1]
如题，请求支持transition。尝试了使用transition过渡动画会报错，微信开发者工具编译不通过

**Comment by AdvancedCat** [comment]
你说的是 Vue.js 内置的 `<Transition>` 组件么？

**Comment by Chandlercjy** [comment]
嗯嗯是的
https://router.vuejs.org/zh/guide/advanced/transitions.html

**Comment by AdvancedCat** [comment]
可以参考一下 `兼容<transition>` https://docs.taro.zone/docs/vue-overall#%E5%85%BC%E5%AE%B9-transition

**Comment by Chandlercjy** [comment]
非常感谢！ 还有一个问题是，使用vue-router后，相当于是一个单页面应用，有没有办法可以监听物理返回键实现顺滑的返回？ 在安卓机上操作，屏幕左滑的话会直接退出小程序

**Comment by AdvancedCat** [comment]
可以从微信小程序官方文档上查找是否有相关事件监听

**Comment by Chandlercjy** [comment]
研究过了，好像没什么好的方案，感谢！
