### ISSUE TITLE
throw new Error('全局配置缺少 pages 字段，请检查！');

### ISSUE THREAD

**Issue by zzyzjc** [AdvancedCat/taro-vue-router#2]
git clone done
npm i
npm run dev:weapp 
`taro-vue-router/node_modules/@tarojs/webpack5-runner/dist/plugins/MiniPlugin.js:410`
`throw new Error('全局配置缺少 pages 字段，请检查！');`

**Comment by houjie1979** [comment]
我直接npm i 安装，然后运行就报这个错误，非得用pnpm吗， 而且还要先安装Taro 仓库？

**Comment by houjie1979** [comment]
> git clone done npm i npm run dev:weapp `taro-vue-router/node_modules/@tarojs/webpack5-runner/dist/plugins/MiniPlugin.js:410` `throw new Error('全局配置缺少 pages 字段，请检查！');`

运行taro -v查看版本，修改package.json，将taro相关版本号全部替换为实际版本。
